export const province = [
  "Aceh",
  "Sumatera Utara",
  "Sumatera Barat",
  "Riau",
  "Kepulauan Riau",
  "Jambi",
  "Sumatera Selatan",
  "Bangka Belitung",
  "Bengkulu",
  "Lampung",
  "DKI Jakarta",
  "Jawa Barat",
  "Banten",
  "Jawa Tengah",
  "DI Yogyakarta",
  "Jawa Timur",
  "Bali",
  "Nusa Tenggara Barat",
  "Nusa Tenggara Timur",
  "Kalimantan Barat",
  "Kalimantan Tengah",
  "Kalimantan Selatan",
  "Kalimantan Timur",
  "Kalimantan Utara",
  "Sulawesi Utara",
  "Gorontalo",
  "Sulawesi Tengah",
  "Sulawesi Barat",
  "Sulawesi Selatan",
  "Sulawesi Tenggara",
  "Maluku",
  "Maluku Utara",
  "Papua Barat",
  "Papua",
  "Papua Tengah",
  "Papua Pegunungan",
  "Papua Selatan",
];

export const city = [
  "Banda Aceh",
  "Medan",
  "Padang",
  "Pekanbaru",
  "Batam",
  "Jambi",
  "Palembang",
  "Pangkal Pinang",
  "Bengkulu",
  "Bandar Lampung",
  "Jakarta",
  "Bandung",
  "Bogor",
  "Depok",
  "Bekasi",
  "Tangerang",
  "Cirebon",
  "Semarang",
  "Surakarta",
  "Yogyakarta",
  "Surabaya",
  "Malang",
  "Denpasar",
  "Mataram",
  "Kupang",
  "Pontianak",
  "Samarinda",
  "Balikpapan",
  "Banjarmasin",
  "Palangkaraya",
  "Tarakan",
  "Manado",
  "Gorontalo",
  "Palu",
  "Makassar",
  "Kendari",
  "Mamuju",
  "Ambon",
  "Ternate",
  "Jayapura",
  "Manokwari",
  "Merauke",
  "Timika",
  "Wamena",
];
